modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "stack_tags"
version = "${version}"
displayName = "Stack Tags"
authors = "linkedto"
description = '''
Adds item tags that set exact max stack sizes (1, 2, 4, 8, 16, 32, 64). Items in these tags will stack to the specified size across all supported loaders.
'''
#logoFile = ""

[[dependencies.stack_tags]]
modId = "forge"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stack_tags]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4, 1.20.4]"
ordering = "NONE"
side = "BOTH"

